version: '3.7'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint: ./app/entrypoint.sh
    volumes:
      - ./static_volume/:/staticfiles
      - ./media_volume/:/mediafiles
      - ./:/usr/src/app
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  static_volume:
  media_volume:
  postgres_data:
