# Generated by Django 4.0.3 on 2022-03-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=1024, verbose_name='description')),
                ('bucket_path', models.CharField(max_length=100, verbose_name='bucket path')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True, verbose_name='upload date time')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='delete time')),
            ],
        ),
    ]
