# Generated by Django 4.0.2 on 2022-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delete time'),
        ),
        migrations.AlterField(
            model_name='video',
            name='bucket_path',
            field=models.CharField(max_length=100, verbose_name='bucket path'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='upload date'),
        ),
    ]
