# Generated by Django 4.0.2 on 2022-03-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_delete_time_alter_video_bucket_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload_date',
            new_name='upload_datetime',
        ),
    ]
