# Generated by Django 4.0.2 on 2022-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_upload_date_video_upload_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='upload date time'),
        ),
    ]
