name: PreCommit

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        env:
          CHECK: ${{ secrets }}
        run: echo CHECK
      - name: Build docker
        run: docker-compose up -d
      - name: PreCommit Check
        run: docker-compose exec -T web pre-commit run --show-diff-on-failure --color=always --all-files
