name: Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        env:
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
          DEBUG: ${{ secrets.DEBUG }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          TIME_ZONE: ${{ secrets.TIME_ZONE }}
          VIDEOS_BUCKET: ${{ secrets.VIDEOS_BUCKET }}
        run: |
          echo ${{ secrets.ALLOWED_HOSTS }} >> .env
          echo ${{ secrets.BUCKET_REGION }} >> .env
          echo ${{ secrets.DEBUG }} >> .env
          echo ${{ secrets.POSTGRES_DB }} >> .env
          echo ${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo ${{ secrets.POSTGRES_USER }} >> .env
          echo ${{ secrets.RDS_DB_NAME }} >> .env
          echo ${{ secrets.RDS_HOSTNAME }} >> .env
          echo ${{ secrets.RDS_PASSWORD }} >> .env
          echo ${{ secrets.RDS_PORT }} >> .env
          echo ${{ secrets.RDS_USERNAME }} >> .env
          echo ${{ secrets.SECRET_KEY }} >> .env
          echo ${{ secrets.SQL_ENGINE }} >> .env
          echo ${{ secrets.TIME_ZONE }} >> .env
          echo ${{ secrets.VIDEOS_BUCKET }} >> .env
      - name: Build docker
        run: docker-compose up -d --build
      - name: Test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web python manage.py test
