name: Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          ${{ secrets }}
          echo ${{ secrets.ALLOWED_HOSTS }} > app/.env
          echo ${{ secrets.POSTGRES_USER }} >> app/.env
          echo ${{ secrets.BUCKET_REGION }} >> app/.env
          echo ${{ secrets.DEBUG }} >> app/.env
          echo ${{ secrets.POSTGRES_DB }} >> app/.env
          echo ${{ secrets.POSTGRES_PASSWORD }} > app/.env
          echo ${{ secrets.POSTGRES_USER }} > app/.env
          echo ${{ secrets.RDS_DB_NAME }} > app/.env
          echo ${{ secrets.RDS_HOSTNAME }} > app/.env
          echo ${{ secrets.RDS_PASSWORD }} > app/.env
          echo ${{ secrets.RDS_PORT }} > app/.env
          echo ${{ secrets.RDS_USERNAME }} > app/.env
          echo ${{ secrets.SECRET_KEY }} > app/.env
          echo ${{ secrets.SQL_ENGINE }} > app/.env
          echo ${{ secrets.TIME_ZONE }} > app/.env
          echo ${{ secrets.VIDEOS_BUCKET }} > app/.env
      - name: Build docker
        run: docker-compose up -d --build
      - name: Test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web python manage.py test
